app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: FLUX绘画机器人
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/siliconflow:0.0.33@6792acf632f24f1c41a3192a78ef181f7149811a8dfd9a16ade984978613f79c
    version: null
kind: app
version: 0.4.0
workflow:
  conversation_variables: []
  environment_variables:
  - description: ''
    id: 72a7d685-be48-4811-9eb4-1b1588791447
    name: apikey
    selector:
    - env
    - apikey
    value: sk-********************************
    value_type: string
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: llm
      id: 1763016006320-source-1763016132507-target
      source: '1763016006320'
      sourceHandle: source
      target: '1763016132507'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: llm
        targetType: code
      id: 1763016132507-source-1763018334876-target
      source: '1763016132507'
      sourceHandle: source
      target: '1763018334876'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: code
        targetType: end
      id: 1763018334876-source-1763018630636-target
      source: '1763018334876'
      sourceHandle: source
      target: '1763018630636'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        selected: false
        title: 开始
        type: start
        variables:
        - default: ''
          hint: ''
          label: text
          max_length: 200
          options: []
          placeholder: ''
          required: true
          type: text-input
          variable: text
      height: 88
      id: '1763016006320'
      position:
        x: 0
        y: 14
      positionAbsolute:
        x: 0
        y: 14
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: 生成绘画提示词
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: Qwen/Qwen3-8B
          provider: langgenius/siliconflow/siliconflow
        prompt_template:
        - id: 2a601243-dab8-4fa0-8d27-a01979fd662f
          role: system
          text: '你是一个基于Flux.1模型的绘画提示词生成机器人。根据用户的中文描述，自动生成符合Flux.1格式的**英文绘画提示词**。 你的目标是生成简洁、精确且生动的英文提示词，以指导Flux.1图像生成模型创作出用户期望的图像。最终输出应仅包含**英文提示词**，无需任何其他解释或信息。
            ### **提示词生成逻辑**： 1. **理解用户需求**：从用户的中文描述中提取关键信息，包括： * **主体/角色**：外貌、动作、表情等。
            * **场景/环境**：背景、光线、天气等。 * **风格/氛围**：艺术风格、情感氛围、配色等。 * **其他元素**：特定物品、背景或特效。
            2. **生成 Flux.1 格式的英文提示词**： * **简洁明了，细节丰富**：提示词需清晰描述核心对象，并包含足够细节以引导模型。
            * **灵活多变**：可以参考以下模板和示例，但需根据具体需求生成多样化的提示词，避免固定化。 * **符合 Flux.1 风格**：提示词必须遵循
            Flux.1 的要求，尽量包含艺术风格、视觉效果、情感氛围的描述，使用与 Flux.1 模型生成相符的关键词和描述模式。 3. **Flux.1
            提示词要点总结**： * **主体描述**：明确图像中核心对象的身份或场景。 * **风格和情感氛围**：确保包含艺术风格、光线、配色、以及图像的氛围等信息。
            * **动态与细节补充**：可包括场景中的动作、情绪、或光影效果等重要细节。 4. **参考提示词模式 (仅供你学习和灵活调整)**： *
            **角色表情集**：An anime [SUBJECT], animated expression reference sheet, character
            design, reference sheet, turnaround, lofi style, soft colors, gentle natural
            linework, key art, range of emotions, happy sad mad scared nervous embarrassed
            confused neutral, hand drawn, award winning anime, fully clothed * **全角度角色视图**：A
            character sheet of [SUBJECT] in different poses and angles, including
            front view, side view, and back view * **80年代复古风格**：blurry polaroid of
            [a simple description of the scene], 1980s. * **智能手机内部展示**：a iphone product
            image showing the iphone standing and inside the screen the image is shown
            * **双重曝光效果**：[Abstract style waterfalls, wildlife] inside the silhouette
            of a [man]’s head that is a double exposure photograph . Non-representational,
            colors and shapes, expression of feelings, imaginative, highly detailed
            * **高质感电影海报**：A digital illustration of a movie poster titled [‘Sad Sax:
            Fury Toad’], [Mad Max] parody poster, featuring [a saxophone-playing toad
            in a post-apocalyptic desert, with a customized car made of musical instruments],
            in the background, [a wasteland with other musical vehicle chases], movie
            title in [a gritty, bold font, dusty and intense color palette]. * **镜面自拍效果**：Phone
            photo: A woman stands in front of a mirror, capturing a selfie. The image
            quality is grainy, with a slight blur softening the details. The lighting
            is dim, casting shadows that obscure her features. [The room is cluttered,
            with clothes strewn across the bed and an unmade blanket. Her expression
            is casual, full of concentration], while the old iPhone struggles to focus,
            giving the photo an authentic, unpolished feel. The mirror shows smudges
            and fingerprints, adding to the raw, everyday atmosphere of the scene.
            * **像素艺术创作**：[Anything you want] pixel art style, pixels, pixel art ###
            **最终输出格式 (非常重要！)**： 1. **你将直接输出生成的英文绘画提示词。** 这是你本次回复的**唯一文本内容**，无需任何其他中文解释或信息。
            2. **紧接着英文提示词，你将输出特殊的图片生成标签：` `**。 --- **问答示例**： **用户输入**：一个80年代复古风格的照片，画面是一个舒适的客厅，有老式家具和柔和的色调。
            **你的输出**：`A blurry polaroid of a 1980s living room, with vintage furniture,
            soft pastel tones, and a nostalgic, grainy texture. The sunlight filters
            through old curtains, casting long, warm shadows on the wooden floor.
            `'
        - id: 96c96d63-74d6-4b36-abbe-7fb44581e295
          role: user
          text: '{{#1763016006320.text#}}'
        selected: false
        title: LLM
        type: llm
        vision:
          enabled: false
      height: 116
      id: '1763016132507'
      position:
        x: 342
        y: 0
      positionAbsolute:
        x: 342
        y: 0
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    - data:
        code: "import requests\nimport json\n\ndef main(prompt: str, apikey: str)\
          \ -> dict:\n    url = \"https://api.siliconflow.cn/v1/image/generations\"\
          \n    headers = {\n        \"accept\": \"application/json\",\n        \"\
          authorization\": f\"Bearer {apikey}\",\n        \"content-type\": \"application/json\"\
          \n    }\n    data = {\n        \"model\": \"black-forest-labs/FLUX.1-schnell\"\
          ,\n        \"prompt\": prompt,\n        \"image_size\": \"1024x1024\"\n\
          \    }\n    response = requests.post(url, headers=headers, data=json.dumps(data))\n\
          \    if response.status_code == 200:\n        result = response.json()[\"\
          images\"][0][\"url\"]\n        markdown_result = f\"![ai]({result})\"\n\
          \        return {\"result\": markdown_result}\n    else:\n        return\
          \ {\"error\": f\"Error: {response.status_code}, {response.text}\"}"
        code_language: python3
        desc: FLUX1绘画
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 代码执行
        type: code
        variables:
        - value_selector:
          - env
          - apikey
          value_type: string
          variable: apikey
        - value_selector:
          - '1763016132507'
          - text
          value_type: string
          variable: prompt
      height: 80
      id: '1763018334876'
      position:
        x: 684
        y: 18
      positionAbsolute:
        x: 684
        y: 18
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    - data:
        desc: 回答
        outputs:
        - value_selector:
          - '1763018334876'
          - result
          value_type: string
          variable: result
        - value_selector: []
          variable: ''
        selected: false
        title: 结束
        type: end
      height: 116
      id: '1763018630636'
      position:
        x: 1026
        y: 0
      positionAbsolute:
        x: 1026
        y: 0
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    viewport:
      x: 133
      y: 156.99999999999997
      zoom: 0.7
  rag_pipeline_variables: []
